language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 7.1
        - php: nightly
    fast_finish: true

install: composer install

script: make test

after_success:
    - bash <(curl -s https://codecov.io/bash)
