version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  php7-1:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-php7.1-dependencies-{{ checksum "composer.json" }}
      - run: composer update --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-php7.1-dependencies-{{ checksum "composer.json" }}
      - run: make test

  php7-2:
    docker:
      - image: circleci/php:7.2-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-php7.2-dependencies-{{ checksum "composer.json" }}
      - run: composer update --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-php7.2-dependencies-{{ checksum "composer.json" }}
      - run: make test
      - codecov/upload:
          file: coverage.xml

  php7-1-lowest:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-php7.1-lowest-dependencies-{{ checksum "composer.json" }}
      - run: composer update --prefer-dist --prefer-lowest
      - save_cache:
          paths:
            - ./vendor
          key: v1-php7.1-lowest-dependencies-{{ checksum "composer.json" }}
      - run: make test

  php7-2-lowest:
    docker:
      - image: circleci/php:7.2-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-php7.2-lowest-dependencies-{{ checksum "composer.json" }}
      - run: composer update --prefer-dist --prefer-lowest
      - save_cache:
          paths:
            - ./vendor
          key: v1-php7.2-lowest-dependencies-{{ checksum "composer.json" }}
      - run: make test

workflows:
  version: 2.1
  all:
    jobs:
      - php7-1
      - php7-2
      - php7-1-lowest
      - php7-2-lowest
