name: Build

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '12 8 * * 0'

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Test
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0]
        composer-flags: ["", "--prefer-lowest"]

    env:
      COMPOSER_ROOT_VERSION: dev-master

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"

      - name: Install dependencies
        id: composer-run
        run: composer update ${{ matrix.composer-flags }}

      - name: Run tests
        run: make test
